services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    env_file:
      - production.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./production.env:/app/.env:ro
    networks:
      - url-shortener-network
    restart: unless-stopped

networks:
  url-shortener-network:
    driver: bridge
    external: true
