services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:3000'
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - url-shortener-network
    restart: unless-stopped

  mongodb:
    image: mongo:6
    ports:
      - '28017:27017'
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=url-shortener
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - url-shortener-network
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - '7379:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - url-shortener-network
    restart: unless-stopped

networks:
  url-shortener-network:
    driver: bridge

volumes:
  mongodb-data:
  redis-data: